# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inspectr < Formula
  desc "Inspectr – Simplifying API and Webhook debugging!"
  homepage "https://github.com/inspectr-hq/inspectr"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inspectr-hq/inspectr/releases/download/v0.2.3/inspectr_0.2.3_darwin_amd64.tar.gz"
      sha256 "4385858ba509beb9c198e32cb212bdbced3d7e9f175910e6db7e535796f17e1c"

      def install
        bin.install "inspectr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inspectr-hq/inspectr/releases/download/v0.2.3/inspectr_0.2.3_darwin_arm64.tar.gz"
      sha256 "3db99de41d9c3a460b73674760e85b70870d5d9d2c600f99eff14b542c2fd050"

      def install
        bin.install "inspectr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/inspectr-hq/inspectr/releases/download/v0.2.3/inspectr_0.2.3_linux_amd64.tar.gz"
        sha256 "8f63a2659021a688a357f766a5019a7026ba1c30a54f2d77aee5e6f45b1f07ad"

        def install
          bin.install "inspectr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/inspectr-hq/inspectr/releases/download/v0.2.3/inspectr_0.2.3_linux_arm64.tar.gz"
        sha256 "ac37199940cfa7f7de0a9c3c6d4dbef5680fa17ac60c3ddc73afdb2ac489a501"

        def install
          bin.install "inspectr"
        end
      end
    end
  end
end
