# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inspectr < Formula
  desc "Inspectr – Simplifying API and Webhook debugging!"
  homepage "https://github.com/inspectr-hq/inspectr"
  version "1.9.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inspectr-hq/inspectr/releases/download/v1.9.2/inspectr_1.9.2_darwin_amd64.tar.gz"
      sha256 "8fb147df576232e51677cc0edd5912845ac9d53e6cae92cd895f4ec3de09e7d1"

      def install
        bin.install "inspectr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inspectr-hq/inspectr/releases/download/v1.9.2/inspectr_1.9.2_darwin_arm64.tar.gz"
      sha256 "da343837b8db4a2888b37c30a47ca2745eea87243eec65962d2d41702ee5d243"

      def install
        bin.install "inspectr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inspectr-hq/inspectr/releases/download/v1.9.2/inspectr_1.9.2_linux_amd64.tar.gz"
      sha256 "831dc8c518eb86937e64de6f6185dbca5f10a5c62fd9c0164706c38e1879ea61"
      def install
        bin.install "inspectr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inspectr-hq/inspectr/releases/download/v1.9.2/inspectr_1.9.2_linux_arm64.tar.gz"
      sha256 "ea11ff6cd9de93ff4d1deeaa5e95ec3242f26b51801b8c5eb2a541f5f4c501e9"
      def install
        bin.install "inspectr"
      end
    end
  end
end
