# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inspectr < Formula
  desc "Inspectr – Simplifying API and Webhook debugging!"
  homepage "https://github.com/inspectr-hq/inspectr"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inspectr-hq/inspectr/releases/download/v0.4.0/inspectr_0.4.0_darwin_amd64.tar.gz"
      sha256 "b2e7216a68dc1d8657408b35bc78e033f8e33e546cf3627e9c100363443063a3"

      def install
        bin.install "inspectr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inspectr-hq/inspectr/releases/download/v0.4.0/inspectr_0.4.0_darwin_arm64.tar.gz"
      sha256 "34202dee0e65d1e493ec5117ec1c04059ebe8c18107120e829c6f4c9dc5b3280"

      def install
        bin.install "inspectr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/inspectr-hq/inspectr/releases/download/v0.4.0/inspectr_0.4.0_linux_amd64.tar.gz"
        sha256 "8f6ed495ccf44198fe784a17fe206c67a533d507f8d814d5fc8e0bb2d60d8904"

        def install
          bin.install "inspectr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/inspectr-hq/inspectr/releases/download/v0.4.0/inspectr_0.4.0_linux_arm64.tar.gz"
        sha256 "3b4995e91ecbb6f667c35cbd420feccd3c9e1093c7fd188ff56280cb2ea72149"

        def install
          bin.install "inspectr"
        end
      end
    end
  end
end
